/** PostgreSQL (self-hosted) provider bundle: local JWT auth + Postgres storage. */
module.exports = {
  authProvider: require('./authProvider'),
  assetService: require('./assetService'),
  handoverService: require('./handoverService'),
  maintenanceService: require('./maintenanceService'),
  dashboardService: require('./dashboardService'),
  employeeService: require('./employeeService'),
  offboardService: require('./offboardService'),
  onboardingService: require('./onboardingService'),
  licenseService: require('./licenseService'),
  consumableService: require('./consumableService'),
  settingsService: require('./settingsService'),
  documentService: require('./documentService'),
  catalogService: require('./catalogService'),
  countService: require('./countService'),
  lineService: require('./lineService'),
  importService: require('./importService'),
  auditService: require('./auditService'),
  providerService: require('./providerService'),
  ensureDatabase: () => require('./migrate').ensureDatabase(),
  ping: (timeoutMs) => require('./pool').ping(timeoutMs),
  isAuthError: (err) => require('./pool').isAuthError(err),
};
