#!/usr/bin/env node
/**
 * ITACM setup — writes a ready-to-run .env for the Docker Compose stack.
 *
 *   npm run setup
 *
 * Choice: (1) New installation  (2) Migrate from package
 * For migrate: asks package path + JWT_SECRET from source, brings stack up, runs migrate-import.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');
const { spawn } = require('child_process');

const ROOT = path.join(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');
const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((r) => rl.question(q, (a) => r(a.trim())));
const askDefault = async (q, d) => (await ask(`${q} [${d}]: `)) || d;

function run(cmd, args, opts = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { stdio: 'inherit', cwd: ROOT, shell: opts.shell || false, ...opts });
    child.on('error', reject);
    child.on('close', (code) => (code === 0 ? resolve() : reject(new Error(`${cmd} exited ${code}`))));
  });
}

async function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

async function waitHealthy(maxMs = 120000) {
  const start = Date.now();
  while (Date.now() - start < maxMs) {
    try {
      await run('docker', ['compose', 'ps', 'api', '--status', 'running'], { stdio: 'ignore' });
      // Hit health endpoint via docker exec or curl
      await new Promise((resolve, reject) => {
        const c = spawn('docker', ['compose', 'exec', '-T', 'api', 'wget', '-qO-', 'http://localhost:8000/api/health'], {
          cwd: ROOT, stdio: ['ignore', 'pipe', 'pipe'],
        });
        let out = '';
        c.stdout.on('data', (d) => { out += d; });
        c.on('close', (code) => {
          if (code === 0 && /"success"\s*:\s*true/.test(out)) resolve();
          else reject(new Error('not healthy'));
        });
        c.on('error', reject);
      });
      return;
    } catch {
      await sleep(2500);
    }
  }
  throw new Error('Timed out waiting for API to become healthy');
}

function writeEnv({ adminEmail, adminUsername, adminPassword, corsOrigins, jwtSecret, dbPassword }) {
  fs.writeFileSync(ENV_PATH, `# Generated by scripts/setup.js — ${new Date().toISOString()}
PORT=8000
API_PORT=8000
${corsOrigins ? `CORS_ORIGINS=${corsOrigins}\n` : ''}
POSTGRES_DB=itacm
POSTGRES_USER=itacm
POSTGRES_PASSWORD=${dbPassword}
DATABASE_URL=postgres://itacm:${dbPassword}@localhost:5432/itacm

JWT_SECRET=${jwtSecret}
JWT_EXPIRES_IN=12h

ADMIN_EMAIL=${adminEmail}
ADMIN_USERNAME=${adminUsername}
ADMIN_PASSWORD=${adminPassword}
`, { mode: 0o600 });
}

async function setupNew() {
  const adminEmail = await askDefault('Admin email', 'admin@example.com');
  const adminUsername = await askDefault('Admin display name', 'IT Admin');
  const adminPassword = await ask('Admin password (leave EMPTY to auto-generate & print in logs): ');
  const corsOrigins = await ask('Extra CORS origin(s), comma separated (blank = same-origin): ');
  const jwtSecret = crypto.randomBytes(32).toString('hex');
  const dbPassword = crypto.randomBytes(16).toString('base64url');
  writeEnv({ adminEmail, adminUsername, adminPassword, corsOrigins, jwtSecret, dbPassword });
  console.log('\n\x1b[32m✔ .env written (JWT secret & DB password generated for you).\x1b[0m');
  console.log('\nNext steps:');
  console.log('  \x1b[1mdocker compose up -d\x1b[0m');
  console.log('  docker compose logs api      \x1b[2m# first-run admin credentials appear here\x1b[0m');
  console.log('  open http://localhost:8000');
  console.log('\nFirst visit: choose New workspace or Migrate from another server.');
}

async function setupMigrate() {
  const pkg = await ask('Path to migration package (.zip / .tar.gz / folder): ');
  if (!pkg || !fs.existsSync(pkg)) {
    console.error('\x1b[31mPackage not found:\x1b[0m', pkg || '(empty)');
    process.exit(1);
  }
  console.log('\n\x1b[33m⚠ JWT_SECRET must match the SOURCE server (required for SMTP password decrypt).\x1b[0m');
  const jwtSecret = await ask('Paste JWT_SECRET from the source .env: ');
  if (!jwtSecret || jwtSecret.length < 32) {
    console.error('JWT_SECRET is required (min 32 chars).');
    process.exit(1);
  }
  const corsOrigins = await ask('Extra CORS origin(s), comma separated (blank = same-origin): ');
  const dbPassword = crypto.randomBytes(16).toString('base64url');
  writeEnv({
    adminEmail: 'admin@example.com',
    adminUsername: 'IT Admin',
    adminPassword: '',
    corsOrigins,
    jwtSecret,
    dbPassword,
  });
  console.log('\n\x1b[32m✔ .env written with source JWT_SECRET.\x1b[0m');
  console.log('  Starting Docker stack…');
  await run('docker', ['compose', 'up', '-d']);
  console.log('  Waiting for API healthy…');
  await waitHealthy();
  console.log('  Running migrate:import…');
  await run('bash', [path.join(ROOT, 'scripts/migrate-import.sh'), pkg, '--yes']);
  console.log('\n\x1b[32m✔ Migration import complete.\x1b[0m');
  console.log('  open http://localhost:8000  — sign in with a restored Owner account.');
}

async function main() {
  console.log('\n  ITACM — IT Asset Control Pro : Setup\n  ------------------------------------');
  console.log('  (1) New installation');
  console.log('  (2) Migrate from package (another server)\n');

  if (fs.existsSync(ENV_PATH)) {
    const ow = await ask('.env already exists. Overwrite? (y/N) ');
    if (ow.toLowerCase() !== 'y') { console.log('Aborted — existing .env kept.'); return rl.close(); }
  }

  const choice = await askDefault('Choose', '1');
  if (choice === '2') await setupMigrate();
  else await setupNew();
  rl.close();
}

main().catch((err) => { console.error(err); rl.close(); process.exit(1); });
