#!/usr/bin/env node
/**
 * ITACM setup — writes a ready-to-run .env for the Docker Compose stack.
 *
 *   npm run setup
 *
 * Generates a strong JWT secret and database password for you, then you just
 * run `docker compose up -d`.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');

const ENV_PATH = path.join(__dirname, '..', '.env');
const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((r) => rl.question(q, (a) => r(a.trim())));
const askDefault = async (q, d) => (await ask(`${q} [${d}]: `)) || d;

async function main() {
  console.log('\n  ITACM — IT Asset Control Pro : Setup\n  ------------------------------------');

  if (fs.existsSync(ENV_PATH)) {
    const ow = await ask('.env already exists. Overwrite? (y/N) ');
    if (ow.toLowerCase() !== 'y') { console.log('Aborted — existing .env kept.'); return rl.close(); }
  }

  const adminEmail = await askDefault('Admin email', 'admin@example.com');
  const adminUsername = await askDefault('Admin display name', 'IT Admin');
  const adminPassword = await ask('Admin password (leave EMPTY to auto-generate & print in logs): ');
  const corsOrigins = await ask('Extra CORS origin(s), comma separated (blank = same-origin): ');

  const jwtSecret = crypto.randomBytes(32).toString('hex');
  const dbPassword = crypto.randomBytes(16).toString('base64url');

  fs.writeFileSync(ENV_PATH, `# Generated by scripts/setup.js — ${new Date().toISOString()}
PORT=8000
API_PORT=8000
${corsOrigins ? `CORS_ORIGINS=${corsOrigins}\n` : ''}
POSTGRES_DB=itacm
POSTGRES_USER=itacm
POSTGRES_PASSWORD=${dbPassword}
DATABASE_URL=postgres://itacm:${dbPassword}@localhost:5432/itacm

JWT_SECRET=${jwtSecret}
JWT_EXPIRES_IN=12h

ADMIN_EMAIL=${adminEmail}
ADMIN_USERNAME=${adminUsername}
ADMIN_PASSWORD=${adminPassword}
`, { mode: 0o600 });

  console.log('\n\x1b[32m✔ .env written (JWT secret & DB password generated for you).\x1b[0m');
  console.log('\nNext steps:');
  console.log('  \x1b[1mdocker compose up -d\x1b[0m');
  console.log('  docker compose logs api      \x1b[2m# first-run admin credentials appear here\x1b[0m');
  console.log('  open http://localhost:8000');
  console.log('\nFirst visit shows the onboarding wizard to create your Owner account.');
  rl.close();
}

main().catch((err) => { console.error(err); rl.close(); process.exit(1); });
